name: pothole reusable CD

on:
  workflow_call:

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ inputs.module }} deploy
    runs-on: ubuntu-22.04

    steps:
      - name: GitHub Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: core application.yml 생성
        shell: bash
        run: |
          mkdir -p ./pothole-core/src/main/resources
          cd ./pothole-core/src/main/resources
          
          touch ./application-core-dev.yml
          echo "${{ secrets.CORE_APPLICATION_DEV_YML }}" > ./application-core-dev.yml

      - name: pothole all build
        run: |
          ./gradlew clean pothole-core:bootJar -x test
          ./gradlew pothole-manager-api:bootJar -x test
          ./gradlew pothole-worker-api:bootJar -x test

      - name: 전체 디렉토리 업로드
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./

      - name: 현재 디렉토리 출력
        run: |
          echo ${{ github.workspace }}
          ls -l