name: pothole all build

on:
  workflow_call:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: pothole build
        run: |
          ./gradlew clean pothole-core:bootJar -x test
          ./gradlew clean pothole-manager-api:bootJar -x test
          ./gradlew clean pothole-worker-api:bootJar -x test

      - name: 현재 디렉토리 출력
        run: |
          echo ${{ github.workspace }}
          ls -l

      - name: github.head_ref 출력
        run: echo ${{ github.head_ref }}