name: CD

on:
  #  pull_request_target:
  #    types:
  #        - closed
  #    branches:
  #      - 'develop'
  push:
    branches: [ "develop" ]

jobs:
#  build_manager:
#    uses: ./.github/workflows/build.yml
#    with:
#      env: manager
  deploy_manager:
#    needs: build_manager
    uses: ./.github/workflows/pothole-manager-CD.yml
    with:
      env: manager
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_IP: ${{ secrets.EC2_IP }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}