name: CD

on:
  #  pull_request_target:
  #    types:
  #        - closed
  #    branches:
  #      - 'develop'
  push:
    branches: [ "develop" ]

jobs:
#  build_manager:
#    uses: ./.github/workflows/build.yml
#    with:
#      env: manager
  deploy_manager:
#    needs: build_manager
    uses: ./.github/workflows/pothole-manager-CD.yml
    with:
      env: manager
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}