name: pothole CD

on:
  pull_request_target:
    types: [closed]
    branches: ["develop"]

jobs:
  build:
    uses: ./.github/workflows/build-CD.yml
    secrets:
      CORE_APPLICATION_DEV_YML: ${{ secrets.CORE_APPLICATION_DEV_YML }}
      MANAGER_APPLICATION_YML: ${{ secrets.MANAGER_APPLICATION_YML }}
      MANAGER_APPLICATION_DEV_YML: ${{ secrets.MANAGER_APPLICATION_DEV_YML }}
      WORKER_APPLICATION_YML: ${{ secrets.WORKER_APPLICATION_YML }}
      WORKER_APPLICATION_DEV_YML: ${{ secrets.WORKER_APPLICATION_DEV_YML }}
    with:
      pr_author: ${{ github.event.pull_request.user.login }}
      pr_title: ${{ github.event.pull_request.title }}
      pr_url: ${{ github.event.pull_request.html_url }}

  deploy_manager:
    if: github.event.pull_request.merged == true
      && (contains(github.head_ref, 'manager') || contains(github.head_ref, 'core'))
    needs: build
    uses: ./.github/workflows/reusable-CD.yml
    with:
      module: manager
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_IP: ${{ secrets.EC2_IP }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}

  deploy_worker:
    if: github.event.pull_request.merged == true
      && (contains(github.head_ref, 'worker') || contains(github.head_ref, 'core'))
    needs: build
    uses: ./.github/workflows/reusable-CD.yml
    with:
      module: worker
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_IP: ${{ secrets.EC2_IP }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}