name: pothole CD

on:
  pull_request:
    branches: [ "develop" ]
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Repository Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_DEVELOPER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEVELOPER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pothole-dev
          IMAGE_TAG: $(date -u +"%Y%m%dT%H%M%SZ")
          AWS_DEFAULT_REGION: ap-northeast-2
          AWS_REGION: ap-northeast-2

        run: |
          # Build a Docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
