name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin' 
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew  # Gradle Wrapper 파일인 gradlew에 실행 권한을 부여하는 명령입니다. 이 명령을 통해 GitHub Actions가 ./gradlew build와 같은 명령을 실행할 수 있게 됩니다. 이 단계는 프로젝트가 Gradle Wrapper를 사용하고 있고, 이 파일이 실행 권한을 갖고 있지 않은 경우에 필요합니다.
    - name: Build with Gradle
      run: ./gradlew build  # Gradle Wrapper를 사용하여 빌드를 실행하는 명령입니다. 이 명령은 프로젝트의 모든 소스 파일을 컴파일하고, 테스트를 실행하며, 실행 가능한 애플리케이션을 생성합니다. 이 단계는 CI 워크플로우에서 중요한 부분으로, 소스 코드가 실제로 컴파일되고 실행되는지 확인합니다.
