name: pothole Build & Test

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Repository Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Pothole [Core] Module Build with Gradle
      run: ./gradlew clean pothole-core:bootJar -x test

    - name: Pothole [Core] Module test
      run: ./gradlew clean pothole-core:test

    - name: Pothole [Manager] Module Build with Gradle
      run: ./gradlew clean pothole-manager-api:bootJar -x test

    - name: Pothole [Manager] Module test
      run: ./gradlew clean pothole-manager-api:test
    
    - name: Pothole [Worker] Module Build with Gradle
      run: ./gradlew clean pothole-worker-api:bootJar -x test

    - name: Pothole [Worker] Module test
      run: ./gradlew clean pothole-worker-api:test
