name: pothole Manager CD

on:
#  pull_request:
#    branches:
#      - 'develop'
#    types:
#      - closed
  push:
    branches: [ "develop", "**/manager/**" ]

jobs:
  deploy:
    #    if: github.event.pull_request.merged == true
#    if: contains(github.head_ref, 'manager') || contains(github.head_ref, 'core')
    name: deploy_manager
    uses: ./.github/workflows/build.yml
    with:
      env: manager

#      - name: EC2 접속, 컨테이너 종료, 삭제, 이미지 삭제
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_IP }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          script: |
#            sudo docker ps -q | xargs -r docker stop
#            sudo docker ps -asq | xargs -r docker rm
#            sudo docker images -q | xargs -r docker rmi
#            sudo docker system prune -af
#
#      - name: EC2에서 도커 이미지를 가져오기
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_IP }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#
#      - name: ECR에서 불러온 이미지를 도커에서 실행
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_IP }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            sudo docker stop pothole-manager || true
#            sudo docker rm pothole-manager || true
#            sudo docker run -d --name pothole-manager -p 8081:8081 $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG