name: pothole Manager CD

on:
  push:
    branches: [ "develop" ]

jobs:
  deploy:
    name: deploy_manager
    runs-on: ubuntu-22.04

    steps:
      - name: GitHub Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: pothole build
        run: ./gradlew clean pothole-manager-api:bootJar -x test

      - name: 현재 디렉토리 출력
        run: |
          echo ${{ github.workspace }}
          ls -l

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Manager Build, tag, and push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pothole-manager
#          IMAGE_TAG: ${{ github. sha }}

        run: |
          cd ./pothole-manager-api
          echo ${{ github.workspace }}
          ls -l

          # Build a Docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"