name: pothole Manager CD

on:
  workflow_call:
    inputs:
      module:
        type: string
        required: true
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      EC2_IP:
        required: true
      EC2_USERNAME:
        required: true
      EC2_SSH_KEY:
        required: true
      CORE_APPLICATION_DEV_YML:
        required: true
      MANAGER_APPLICATION_YML:
        required: true
      MANAGER_APPLICATION_DEV_YML:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: ${{ inputs.module }} deploy
    runs-on: ubuntu-22.04

    steps:
      - name: GitHub Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: core application.yml 생성
        shell: bash
        run: |
          mkdir -p ./pothole-core/src/main/resources
          cd ./pothole-core/src/main/resources
          
          touch ./application-core-dev.yml
          echo "${{ secrets.CORE_APPLICATION_DEV_YML }}" > ./application-core-dev.yml

      - name: ${{ inputs.module }} application.yml 생성
        if: ${{ inputs.module }} == 'manager'
        shell: bash
        run: |
          mkdir -p ./pothole-manager-api/src/main/resources
          cd ./pothole-manager-api/src/main/resources
          
          touch ./application.yml
          echo "${{ secrets.MANAGER_APPLICATION_YML }}" > ./application.yml
          
          touch ./application-aws.yml
          echo "${{ secrets.MANAGER_APPLICATION_DEV_YML }}" > ./application-manager-dev.yml

      - name: pothole build
        run: |
          ./gradlew clean pothole-core:bootJar -x test
          ./gradlew clean pothole-manager-api:bootJar -x test

      - name: 현재 디렉토리 출력
        run: |
          echo ${{ github.workspace }}
          ls -l

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: ${{ inputs.module }} Build, tag, and push the image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pothole-${{ inputs.module }}
#          IMAGE_TAG: ${{ github. sha }}

        run: |
          cd ./pothole-${{ inputs.module }}-api
          echo ${{ github.workspace }}
          ls -l

          # Build a Docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

          echo "Pushing image to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: 현재 디렉토리 출력
        run: |
          echo ${{ github.workspace }}
          ls -l

      - name: docker-compose.yml 파일 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/home/ubuntu/"

      - name: docker compose down [Manager] on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker compose down pothole-${{ inputs.module }}

      - name: pull image from ECR
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 339712790479.dkr.ecr.ap-northeast-2.amazonaws.com
            
            docker pull ${{ steps.login-ecr.outputs.registry }}/pothole-${{ inputs.module }}:latest
            docker image tag ${{ steps.login-ecr.outputs.registry }}/pothole-${{ inputs.module }}:latest pothole-manager-api

      - name: docker compose up [Manager] on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker-compose up -d pothole-${{ inputs.module }}
            docker image prune -f